#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""FQGate 能力元数据（唯一真源）。

按 FQGate OpenAPI（v1.0.5）整理 17 个分组的全部端点，供：
- core.datasource.registry 生成数据源 capabilities 展示；
- 后续能力探测/文档页/Agent 工具描述复用。

字段：path/method/summary/description；auth_required 标记需登录行情账户；
level2 标记需 Level-2 权限。
"""

CAPABILITY_GROUPS: list[dict] = [
    {
        "key": 'calendar',
        "name": '交易日历',
        "endpoints": [
            {
                "path": '/v1/market/calendar/timeline',
                "method": 'POST',
                "summary": '市场时间轴',
                "description": '返回指定证券所属市场的交易日、时区和交易时段。不提供证券当前交易状态。',
                "auth_required": False,
                "level2": False,
            },
            {
                "path": '/v1/market/calendar/trading-days',
                "method": 'POST',
                "summary": '交易日',
                "description": '返回指定日期范围内的交易日，无需登录行情账户。',
                "auth_required": False,
                "level2": False,
            },
        ],
    },
    {
        "key": 'catalog',
        "name": '证券与板块',
        "endpoints": [
            {
                "path": '/v1/market/catalog/block',
                "method": 'POST',
                "summary": '板块详情',
                "description": '根据板块目录中的编号返回板块信息，支持分页。',
                "auth_required": False,
                "level2": False,
            },
            {
                "path": '/v1/market/catalog/block-constituents',
                "method": 'POST',
                "summary": '板块成分证券',
                "description": '返回指定板块的成分证券，支持分页。请使用板块详情中的完整板块代码。',
                "auth_required": False,
                "level2": False,
            },
            {
                "path": '/v1/market/catalog/bond',
                "method": 'POST',
                "summary": '债券目录',
                "description": '返回可查询的债券目录，单页默认返回 50 条。',
                "auth_required": False,
                "level2": False,
            },
            {
                "path": '/v1/market/catalog/complete-code',
                "method": 'POST',
                "summary": '证券代码补全',
                "description": '支持补全一个或多个证券代码，两种输入方式不能同时使用。',
                "auth_required": False,
                "level2": False,
            },
            {
                "path": '/v1/market/catalog/forex',
                "method": 'POST',
                "summary": '外汇目录',
                "description": '返回可查询的外汇品种目录，单页默认返回 50 条。',
                "auth_required": False,
                "level2": False,
            },
            {
                "path": '/v1/market/catalog/fund-etf',
                "method": 'POST',
                "summary": 'ETF 目录',
                "description": '返回可查询的 ETF 目录，单页默认返回 50 条。',
                "auth_required": False,
                "level2": False,
            },
            {
                "path": '/v1/market/catalog/fund-etf-t0',
                "method": 'POST',
                "summary": 'T+0 ETF 目录',
                "description": '返回可 T+0 交易的 ETF 目录，单页默认返回 50 条。',
                "auth_required": False,
                "level2": False,
            },
            {
                "path": '/v1/market/catalog/futures',
                "method": 'POST',
                "summary": '期货合约目录',
                "description": '返回可查询的期货合约目录，单页默认返回 50 条。',
                "auth_required": False,
                "level2": False,
            },
            {
                "path": '/v1/market/catalog/index',
                "method": 'POST',
                "summary": '指数目录',
                "description": '返回可查询的指数目录，单页默认返回 50 条。',
                "auth_required": False,
                "level2": False,
            },
            {
                "path": '/v1/market/catalog/market-block',
                "method": 'POST',
                "summary": '板块目录',
                "description": '返回指定市场的板块目录，支持分页。',
                "auth_required": False,
                "level2": False,
            },
            {
                "path": '/v1/market/catalog/nasdaq',
                "method": 'POST',
                "summary": '纳斯达克证券目录',
                "description": '返回可查询的纳斯达克证券目录，单页默认返回 50 条。',
                "auth_required": False,
                "level2": False,
            },
            {
                "path": '/v1/market/catalog/related-securities',
                "method": 'POST',
                "summary": '关联证券',
                "description": '返回 A 股与 H 股对应证券、期货关联证券或期货与股票关联目录。',
                "auth_required": False,
                "level2": False,
            },
            {
                "path": '/v1/market/catalog/related-securities/list',
                "method": 'POST',
                "summary": '证券关联列表',
                "description": '返回证券关联的板块等项目，记录可能使用 URFI、URFA 等板块市场代码。支持分页，单页默认最多 20 条，默认按名称字段 55 降序排列。',
                "auth_required": False,
                "level2": False,
            },
            {
                "path": '/v1/market/catalog/search-symbols',
                "method": 'POST',
                "summary": '搜索证券',
                "description": '按证券名称或代码片段搜索证券。',
                "auth_required": False,
                "level2": False,
            },
            {
                "path": '/v1/market/catalog/security-blocks',
                "method": 'POST',
                "summary": '证券所属板块',
                "description": '返回指定证券所属的板块。',
                "auth_required": False,
                "level2": False,
            },
            {
                "path": '/v1/market/catalog/security-industries',
                "method": 'POST',
                "summary": '证券所属行业',
                "description": '返回一只或多只证券所属的行业。',
                "auth_required": False,
                "level2": False,
            },
            {
                "path": '/v1/market/catalog/stock-b',
                "method": 'POST',
                "summary": 'B 股证券目录',
                "description": '返回可查询的 B 股证券目录，单页默认返回 50 条。',
                "auth_required": False,
                "level2": False,
            },
            {
                "path": '/v1/market/catalog/stock-bj',
                "method": 'POST',
                "summary": '北交所证券目录',
                "description": '返回可查询的北交所证券目录，单页默认返回 50 条。',
                "auth_required": False,
                "level2": False,
            },
            {
                "path": '/v1/market/catalog/stock-cn',
                "method": 'POST',
                "summary": '沪深证券目录',
                "description": '返回可查询的沪深证券目录，单页默认返回 50 条。',
                "auth_required": False,
                "level2": False,
            },
            {
                "path": '/v1/market/catalog/stock-hk',
                "method": 'POST',
                "summary": '港股证券目录',
                "description": '返回可查询的港股证券目录，单页默认返回 50 条。',
                "auth_required": False,
                "level2": False,
            },
            {
                "path": '/v1/market/catalog/stock-uk',
                "method": 'POST',
                "summary": '英股证券目录',
                "description": '返回可查询的英股证券目录，单页默认返回 50 条。',
                "auth_required": False,
                "level2": False,
            },
            {
                "path": '/v1/market/catalog/stock-us',
                "method": 'POST',
                "summary": '美股证券目录',
                "description": '返回可查询的美股证券目录，单页默认返回 50 条。',
                "auth_required": False,
                "level2": False,
            },
            {
                "path": '/v1/market/catalog/ths-concept',
                "method": 'POST',
                "summary": '同花顺概念目录',
                "description": '返回同花顺概念板块记录，单页默认返回 50 条。',
                "auth_required": False,
                "level2": False,
            },
            {
                "path": '/v1/market/catalog/ths-industry',
                "method": 'POST',
                "summary": '同花顺行业目录',
                "description": '返回同花顺行业板块记录，单页默认返回 50 条。',
                "auth_required": False,
                "level2": False,
            },
        ],
    },
    {
        "key": 'session',
        "name": '账户与登录',
        "endpoints": [
            {
                "path": '/v1/market/health',
                "method": 'GET',
                "summary": '登录状态',
                "description": '返回当前行情账户的登录状态。行情账户与交易账户分别登录。',
                "auth_required": True,
                "level2": False,
            },
            {
                "path": '/v1/market/session',
                "method": 'DELETE',
                "summary": '退出登录',
                "description": '退出当前行情账户。',
                "auth_required": True,
                "level2": False,
            },
            {
                "path": '/v1/market/session/cached-login',
                "method": 'POST',
                "summary": '本机快捷登录',
                "description": '通过 client_path 指定运行 FQGate 的电脑上的同花顺安装目录，复用该客户端最近账号已保存的登录凭据。当前支持 Windows 远航版的 MD5/临时凭据记录；未保存、已过期或认证格式不支持会明确提示。登录成功后自动保存恢复信息，后续行情请求及主程序重启后均自动恢复，无需重复调用本接口。',
                "auth_required": True,
                "level2": False,
            },
            {
                "path": '/v1/market/session/login',
                "method": 'POST',
                "summary": '账号密码登录',
                "description": '使用同花顺账号和密码登录行情账户。密码不会在响应中返回。',
                "auth_required": True,
                "level2": False,
            },
            {
                "path": '/v1/market/session/qr/begin',
                "method": 'POST',
                "summary": 'App 扫码登录：获取二维码',
                "description": '返回登录二维码和登录流程编号。请使用同花顺 App 扫码并在手机上确认。',
                "auth_required": True,
                "level2": False,
            },
            {
                "path": '/v1/market/session/qr/poll',
                "method": 'POST',
                "summary": 'App 扫码登录：查询扫码状态',
                "description": '查询一次扫码登录进度；未完成时可间隔一段时间再次查询。',
                "auth_required": True,
                "level2": False,
            },
            {
                "path": '/v1/market/session/saved-login',
                "method": 'DELETE',
                "summary": '移除保存的登录信息',
                "description": '移除当前系统用户安全存储中的行情登录信息，不中断当前行情连接。',
                "auth_required": True,
                "level2": False,
            },
            {
                "path": '/v1/market/session/self-stock',
                "method": 'GET',
                "summary": '同花顺自选股',
                "description": '读取当前登录同花顺账号维护的自选股列表。此接口只读，不修改自选股；未登录或登录会话失效时返回错误。',
                "auth_required": True,
                "level2": False,
            },
            {
                "path": '/v1/market/session/self-stock',
                "method": 'POST',
                "summary": '添加到同花顺自选股',
                "description": '将证券添加到当前登录同花顺账号的自选股。未提供 group_id 时写入默认自选；提供自定义分组的 group_id 时写入指定分组。需要正式账号登录，请避免短时间重复提交，本接口不自动重试。',
                "auth_required": True,
                "level2": False,
            },
            {
                "path": '/v1/market/session/self-stock',
                "method": 'DELETE',
                "summary": '从同花顺自选股删除',
                "description": '从当前登录同花顺账号的自选股删除证券。未提供 group_id 时操作默认自选；提供自定义分组的 group_id 时操作指定分组。需要正式账号登录，请避免短时间重复提交，本接口不自动重试。',
                "auth_required": True,
                "level2": False,
            },
            {
                "path": '/v1/market/session/self-stock/groups',
                "method": 'GET',
                "summary": '查询同花顺自选股分组',
                "description": '读取当前登录同花顺账号的自选股分组及分组内证券。内置分组会标记为只读；未登录或登录会话失效时返回错误。',
                "auth_required": True,
                "level2": False,
            },
            {
                "path": '/v1/market/session/self-stock/groups',
                "method": 'POST',
                "summary": '创建同花顺自选股分组',
                "description": '在当前登录同花顺账号中创建自选股分组。需要正式账号登录；分组版本由服务自动读取，请避免短时间重复提交。',
                "auth_required": True,
                "level2": False,
            },
            {
                "path": '/v1/market/session/self-stock/groups',
                "method": 'DELETE',
                "summary": '删除同花顺自选股分组',
                "description": '删除当前登录同花顺账号中的自选股分组。内置只读分组不能删除；请避免短时间重复提交。',
                "auth_required": True,
                "level2": False,
            },
            {
                "path": '/v1/market/session/sms/begin',
                "method": 'POST',
                "summary": '手机短信登录：获取滑块验证码',
                "description": '返回滑块验证底图、滑块图片及登录流程编号。完成滑块后，请使用同一流程编号获取短信验证码。',
                "auth_required": True,
                "level2": False,
            },
            {
                "path": '/v1/market/session/sms/complete',
                "method": 'POST',
                "summary": '手机短信登录：验证码登录',
                "description": '提交短信验证码并登录行情账户；成功后自动为当前系统用户安全保存登录信息。',
                "auth_required": True,
                "level2": False,
            },
            {
                "path": '/v1/market/session/sms/send-code',
                "method": 'POST',
                "summary": '手机短信登录：获取短信验证码',
                "description": '提交拼图相对底图左上角的最终坐标，并向登录手机号发送验证码。每次请求发送一条短信。',
                "auth_required": True,
                "level2": False,
            },
        ],
    },
    {
        "key": 'auction',
        "name": '集合竞价',
        "endpoints": [
            {
                "path": '/v1/market/history/call-auction',
                "method": 'POST',
                "summary": '集合竞价数据',
                "description": '返回指定证券的集合竞价数据。',
                "auth_required": False,
                "level2": False,
            },
            {
                "path": '/v1/market/history/call-auction-anomaly',
                "method": 'POST',
                "summary": '集合竞价异动',
                "description": '返回指定市场的集合竞价异动；省略市场时查询沪市 A 股。',
                "auth_required": False,
                "level2": False,
            },
        ],
    },
    {
        "key": 'kline',
        "name": 'K 线与分时',
        "endpoints": [
            {
                "path": '/v1/market/history/corporate-action',
                "method": 'POST',
                "summary": '除权除息数据',
                "description": '返回指定证券的除权除息记录。',
                "auth_required": False,
                "level2": False,
            },
            {
                "path": '/v1/market/history/intraday',
                "method": 'POST',
                "summary": '当日分时数据',
                "description": '返回指定证券的当日分时数据。',
                "auth_required": False,
                "level2": False,
            },
            {
                "path": '/v1/market/history/klines',
                "method": 'POST',
                "summary": 'K 线数据',
                "description": '支持按返回数量或日期范围查询，两种查询方式不能同时使用。',
                "auth_required": False,
                "level2": False,
            },
            {
                "path": '/v1/market/history/minute-snapshot',
                "method": 'POST',
                "summary": '分钟快照',
                "description": '返回指定证券的分钟行情快照，可选择交易日。',
                "auth_required": False,
                "level2": False,
            },
        ],
    },
    {
        "key": 'tick',
        "name": '盘口与逐笔',
        "endpoints": [
            {
                "path": '/v1/market/history/depth',
                "method": 'POST',
                "summary": '五档盘口',
                "description": '返回买卖五档价格及数量，不包含每档的逐笔委托队列。',
                "auth_required": False,
                "level2": False,
            },
            {
                "path": '/v1/market/history/super-tick',
                "method": 'POST',
                "summary": '扩展成交明细',
                "description": '返回指定证券的增强逐笔行情，可选择交易日。records 按数据段保留：除逐笔行情外，还可能包含按日提供的补充数据。逐笔段的字段 1 为 Unix 秒时间戳；日级补充段的字段 1 为 YYYYMMDD 日期，可能早于所选交易日。请勿将补充段计入逐笔条数；row_count 为所有段的总行数。',
                "auth_required": False,
                "level2": False,
            },
            {
                "path": '/v1/market/history/tick',
                "method": 'POST',
                "summary": '普通成交明细',
                "description": '返回指定证券的普通成交明细，保留行情服务的记录粒度；不提供 Level-2 原始逐笔成交。',
                "auth_required": False,
                "level2": True,
            },
            {
                "path": '/v1/market/order-book/ask',
                "method": 'POST',
                "summary": '卖方委托队列',
                "description": '返回查询时点的卖方盘口，最多二十档；每档包含逐项委托数量。',
                "auth_required": False,
                "level2": False,
            },
            {
                "path": '/v1/market/order-book/bid',
                "method": 'POST',
                "summary": '买方委托队列',
                "description": '返回查询时点的买方盘口，最多二十档；每档包含逐项委托数量。',
                "auth_required": False,
                "level2": False,
            },
        ],
    },
    {
        "key": 'financial',
        "name": '财务数据',
        "endpoints": [
            {
                "path": '/v1/market/history/financial',
                "method": 'POST',
                "summary": '财务历史',
                "description": '返回指定证券的财务历史记录。支持按记录数量或日期范围查询；省略两者时返回全部可用记录。',
                "auth_required": False,
                "level2": False,
            },
        ],
    },
    {
        "key": 'tas',
        "name": '历史行情',
        "endpoints": [
            {
                "path": '/v1/market/history/tas-transactions',
                "method": 'POST',
                "summary": 'TAS 期货成交明细',
                "description": '查询支持 TAS（结算价交易）的期货成交明细。先从期货目录取得实际合约，再通过字段 144 确认 TAS 标识。空记录表示当前行情服务未返回数据。',
                "auth_required": False,
                "level2": False,
            },
        ],
    },
    {
        "key": 'information',
        "name": '资讯',
        "endpoints": [
            {
                "path": '/v1/market/information/categories',
                "method": 'POST',
                "summary": '资讯分类',
                "description": '返回资讯来源及其分类层级。',
                "auth_required": False,
                "level2": False,
            },
            {
                "path": '/v1/market/information/document',
                "method": 'POST',
                "summary": '证券资讯文档',
                "description": '按资讯分类编号返回指定证券的资讯内容；例如 14341 为公告。text_id 不是单篇文档编号，可选择仅返回摘要。',
                "auth_required": False,
                "level2": False,
            },
            {
                "path": '/v1/market/information/major-events',
                "method": 'POST',
                "summary": '证券重大事件',
                "description": '返回指定证券在日期范围内的重大事件。',
                "auth_required": False,
                "level2": False,
            },
            {
                "path": '/v1/market/information/news',
                "method": 'POST',
                "summary": '证券资讯',
                "description": '返回证券资讯列表及阅读地址。返回的 XML 在每条资讯的 id 后补充 url，其他字段保持不变。可将上一次响应中的资讯时间作为 last_text_time 继续读取。',
                "auth_required": False,
                "level2": False,
            },
            {
                "path": '/v1/market/information/stock-comments',
                "method": 'POST',
                "summary": '个股评论',
                "description": '返回指定证券最近二十四小时的个股评论。',
                "auth_required": False,
                "level2": False,
            },
        ],
    },
    {
        "key": 'ipo',
        "name": '新股信息',
        "endpoints": [
            {
                "path": '/v1/market/information/ipo-pending',
                "method": 'POST',
                "summary": '待申购新股',
                "description": '返回当前可申购或即将申购的新股，无需登录行情账户。',
                "auth_required": False,
                "level2": False,
            },
            {
                "path": '/v1/market/information/ipo-today',
                "method": 'POST',
                "summary": '今日新股',
                "description": '返回今日发行的新股，无需登录行情账户。',
                "auth_required": False,
                "level2": False,
            },
        ],
    },
    {
        "key": 'level2',
        "name": 'Level-2',
        "endpoints": [
            {
                "path": '/v1/market/level2/best-ask-queue',
                "method": 'POST',
                "summary": '卖方委托队列',
                "description": '返回指定证券卖一档的逐项委托数量及队列信息。',
                "auth_required": False,
                "level2": True,
            },
            {
                "path": '/v1/market/level2/best-bid-queue',
                "method": 'POST',
                "summary": '买方委托队列',
                "description": '返回指定证券买一档的逐项委托数量及队列信息。',
                "auth_required": False,
                "level2": True,
            },
            {
                "path": '/v1/market/level2/cancellations/buy',
                "method": 'POST',
                "summary": '买入撤单',
                "description": '返回指定证券买入方向的撤单明细，查询范围可使用 `all` 或 `recent`。  `fields` 推荐填写字段名称：`order_no`、`latest_price`、`price`、`volume`、`amount`、`request_time`、`cancel_time`。方向由接口类型确定，结果中的 `semantic_records[].derived.side` 为 `buy`。  响应中的 `semantic_profile.fields` 给出当前记录类型全部已确认字段的名称、编号和含义。数字字段编号仍可用于兼容；尚未命名的编号会在语义记录中保留为 `Field_编号`。',
                "auth_required": False,
                "level2": True,
            },
            {
                "path": '/v1/market/level2/cancellations/sell',
                "method": 'POST',
                "summary": '卖出撤单',
                "description": '返回指定证券卖出方向的撤单明细，查询范围可使用 `all` 或 `recent`。  `fields` 推荐填写字段名称：`order_no`、`latest_price`、`price`、`volume`、`amount`、`request_time`、`cancel_time`。方向由接口类型确定，结果中的 `semantic_records[].derived.side` 为 `sell`。  响应中的 `semantic_profile.fields` 给出当前记录类型全部已确认字段的名称、编号和含义。数字字段编号仍可用于兼容；尚未命名的编号会在语义记录中保留为 `Field_编号`。',
                "auth_required": False,
                "level2": True,
            },
            {
                "path": '/v1/market/level2/depth',
                "method": 'POST',
                "summary": '十档盘口',
                "description": '返回指定证券的买一至买十、卖一至卖十价格与委托数量，并保留完整行情字段。',
                "auth_required": False,
                "level2": True,
            },
            {
                "path": '/v1/market/level2/enhanced-transactions',
                "method": 'POST',
                "summary": 'TAS 成交明细兼容入口',
                "description": '兼容旧 enhanced_transactions 名称，实际查询 TAS 期货成交明细，不提供 A 股增强逐笔成交。新请求请使用 /v1/market/history/tas-transactions。',
                "auth_required": False,
                "level2": True,
            },
            {
                "path": '/v1/market/level2/order-detail-by-sequence',
                "method": 'POST',
                "summary": '逐笔委托详情',
                "description": '根据证券和逐笔委托序号返回对应的委托详情。',
                "auth_required": False,
                "level2": True,
            },
            {
                "path": '/v1/market/level2/orders',
                "method": 'POST',
                "summary": '逐笔委托',
                "description": '返回指定证券的逐笔委托，查询范围可使用 `all` 或 `recent`。  `fields` 推荐填写字段名称：`order_no`、`price`、`side`、`volclass`、`volume`、`amount`、`order_time`、`request_time`。其中 `side` 会请求原始 `volclass` 字段；结果位于 `semantic_records[].derived.side`，价格类型同时位于 `derived.is_market_price` 和 `derived.is_best_price`。  响应中的 `semantic_profile.fields` 给出当前记录类型全部已确认字段的名称、编号和含义。数字字段编号仍可用于兼容；尚未命名的编号会在语义记录中保留为 `Field_编号`。',
                "auth_required": False,
                "level2": True,
            },
            {
                "path": '/v1/market/level2/transactions',
                "method": 'POST',
                "summary": '逐笔成交',
                "description": '返回指定证券的逐笔成交。`market` 和 `code` 指定证券，`fields` 指定返回字段。  ### 查询方式  - 按数量：填写 `count` 和 `end_time`。`end_time=0` 表示查询最新记录。 - 按时间区间：填写 `start_time` 和 `end_time`，不填写 `count`。 - 时间均为 UTC Unix 秒，不是北京时间的 HHmmss，也不是毫秒。两种查询方式不可混用。  `count` 单次最多 2000 条，超过上限返回参数错误。通常填写 1 至 2000，查询截止时间之前的最近记录。负数和零保留原有参数行为，不作为最近 N 条使用；负数的绝对值同样不得超过 2000。旧 `range.count` 遵循相同限制。按起止时间查询不使用 `count`，不受此数量参数限制。  按数量查询示例：  ```json {"market":"USHA","code":"600519","fields":["price","side","volume","trade_time"],"count":50,"end_time":0} ```  按时间区间查询示例（北京时间 2026-09-08 14:45:00 至 14:50:59）：  ```json {"market":"USHA","code":"600519","fields":["price","side","volume","trade_time"],"start_time":1788849900,"end_time":1788850259} ```  旧 `range` 参数保留兼容，不能与上述三个参数混用。不提供页码或偏移量参数。`trade_date` 只补充可读时间的交易日，不替代查询起止时间。  `fields` 推荐填写字段名称：`source_tick_id`、`market_type`、`full_code`、`price`、`side`、`volclass`、`volume`、`transaction_count`、`raw_transaction_amount`、`trade_time`、`buy_order_no`、`sell_order_no`。其中 `side` 会请求原始 `volclass` 字段；结果位于 `semantic_records[].derived.side`，原始标志仍保留在 `semantic_records[].values.volclass`。  成交方向中，`volclass=1` 对应 `side=sell`，`volclass=5` 对应 `side=buy`，其他值为 `unknown`。逐笔成交不提供委托价格类型标记。  正数 `count` 最多返回指定数量的最新记录。`row_count` 是本次实际返回数量；发生裁剪时，`upstream_row_count` 是裁剪前收到的记录数量，两者都不表示该证券全天的成交总笔数。  省略 `semantic` 时默认按 `true` 处理。响应中的 `records` 始终保留数字字段编号，供兼容和原始数据核对；同时返回的 `semantic_records` 使用可读字段名。`semantic_profile.fields` 给出当前记录类型全部已确认字段的名称、编号和含义。数字字段编号仍可用于兼容；尚未命名的编号会在语义记录中保留为 `Field_编号`。',
                "auth_required": False,
                "level2": True,
            },
        ],
    },
    {
        "key": 'rankings',
        "name": '排行榜',
        "endpoints": [
            {
                "path": '/v1/market/level2/bid-ask-rank',
                "method": 'POST',
                "summary": '买卖盘排名',
                "description": '返回指定证券的买卖盘排名数据，需要 Level-2 权限。需要持续接收变化时，请使用实时订阅中的 bid_ask_rank 类型。',
                "auth_required": False,
                "level2": True,
            },
            {
                "path": '/v1/market/rankings/block',
                "method": 'POST',
                "summary": '板块排行',
                "description": '按指定行情字段返回一个板块内的证券排行。板块编号来自证券与板块目录，支持设置起始位置、返回数量和排序方向。',
                "auth_required": False,
                "level2": False,
            },
            {
                "path": '/v1/market/rankings/market',
                "method": 'POST',
                "summary": '市场排行',
                "description": '按指定行情字段返回一个市场内的证券排行，支持设置起始位置、返回数量和排序方向。常用排序字段包括涨跌幅 199112、成交额 19、五分钟涨速 48 和人气排名 900232。',
                "auth_required": False,
                "level2": False,
            },
            {
                "path": '/v1/market/rankings/securities',
                "method": 'POST',
                "summary": '指定证券排行',
                "description": '按指定行情字段对证券列表排序，并返回所选范围内的结果。起始位置默认为 0，单页默认返回 50 条。',
                "auth_required": False,
                "level2": False,
            },
        ],
    },
    {
        "key": 'options',
        "name": '期权',
        "endpoints": [
            {
                "path": '/v1/market/options/contracts',
                "method": 'POST',
                "summary": '期权合约列表',
                "description": '根据标的证券返回可查询的期权合约。',
                "auth_required": False,
                "level2": False,
            },
            {
                "path": '/v1/market/options/data',
                "method": 'POST',
                "summary": '期权合约行情',
                "description": '返回期权合约行情。请传入期权合约代码，而非标的证券代码。',
                "auth_required": False,
                "level2": False,
            },
            {
                "path": '/v1/market/options/products',
                "method": 'POST',
                "summary": '期权品种目录',
                "description": '返回可查询的期权品种及其标的信息。具体合约请通过期权合约列表查询。',
                "auth_required": False,
                "level2": False,
            },
        ],
    },
    {
        "key": 'realtime',
        "name": '行情',
        "endpoints": [
            {
                "path": '/v1/market/realtime/block',
                "method": 'POST',
                "summary": '板块行情',
                "description": '按常用字段返回板块实时行情。',
                "auth_required": False,
                "level2": False,
            },
            {
                "path": '/v1/market/realtime/bond',
                "method": 'POST',
                "summary": '债券行情',
                "description": '按常用字段返回债券实时行情。',
                "auth_required": False,
                "level2": False,
            },
            {
                "path": '/v1/market/realtime/cn',
                "method": 'POST',
                "summary": '沪深京行情',
                "description": '按常用字段返回沪深京证券实时行情。',
                "auth_required": False,
                "level2": False,
            },
            {
                "path": '/v1/market/realtime/forex',
                "method": 'POST',
                "summary": '外汇行情',
                "description": '按常用字段返回外汇实时行情。',
                "auth_required": False,
                "level2": False,
            },
            {
                "path": '/v1/market/realtime/fund',
                "method": 'POST',
                "summary": '基金行情',
                "description": '按常用字段返回基金实时行情。',
                "auth_required": False,
                "level2": False,
            },
            {
                "path": '/v1/market/realtime/future',
                "method": 'POST',
                "summary": '期货行情',
                "description": '按常用字段返回期货实时行情。',
                "auth_required": False,
                "level2": False,
            },
            {
                "path": '/v1/market/realtime/hk',
                "method": 'POST',
                "summary": '港股行情',
                "description": '按常用字段返回港股实时行情。',
                "auth_required": False,
                "level2": False,
            },
            {
                "path": '/v1/market/realtime/index',
                "method": 'POST',
                "summary": '指数行情',
                "description": '按常用字段返回指数实时行情。',
                "auth_required": False,
                "level2": False,
            },
            {
                "path": '/v1/market/realtime/quote',
                "method": 'POST',
                "summary": '自选字段行情',
                "description": '按指定字段查询实时行情。同一次请求中的证券须属于同一市场。',
                "auth_required": False,
                "level2": False,
            },
            {
                "path": '/v1/market/realtime/trading-status',
                "method": 'POST',
                "summary": '市场时间轴（兼容入口）',
                "description": '旧路径的兼容入口，实际返回市场时间轴，不含证券当前交易状态。新调用请使用 /v1/market/calendar/timeline。',
                "auth_required": False,
                "level2": False,
            },
            {
                "path": '/v1/market/realtime/uk',
                "method": 'POST',
                "summary": '英股行情',
                "description": '按常用字段返回英股实时行情。',
                "auth_required": False,
                "level2": False,
            },
            {
                "path": '/v1/market/realtime/us',
                "method": 'POST',
                "summary": '美股行情',
                "description": '按常用字段返回美股实时行情。',
                "auth_required": False,
                "level2": False,
            },
        ],
    },
    {
        "key": 'selection',
        "name": '选股',
        "endpoints": [
            {
                "path": '/v1/market/selection/wencai-base',
                "method": 'POST',
                "summary": '问财条件选股',
                "description": '根据选股条件返回匹配结果。使用前须登录行情账户。',
                "auth_required": True,
                "level2": False,
            },
            {
                "path": '/v1/market/selection/wencai-nlp',
                "method": 'POST',
                "summary": '问财自然语言选股',
                "description": '使用自然语言描述选股条件并返回匹配结果，无需登录行情账户。',
                "auth_required": False,
                "level2": False,
            },
        ],
    },
    {
        "key": 'stream',
        "name": '盯盘',
        "endpoints": [
            {
                "path": '/v1/market/stream',
                "method": 'GET',
                "summary": '标准订阅接口',
                "description": ' 使用一条 WebSocket 连接订阅多只证券和多种实时数据。连接建立后，客户端通过 JSON 指令新增或取消订阅；每次订阅成功都会取得独立的 `subscription_id`。  ## 建立连接  - 地址：`ws://127.0.0.1:17281/v1/market/stream` - 一条连接可以连续发送多条订阅指令，无需为不同证券或不同数据类型重复建立连接。  ## 标准订阅指令  除短线精灵外，订阅指令均使用 `kind`、`market` 和 `code`。逐笔成交、逐笔委托和撤单的 `fields` 推荐填写字段名称；其他行情类型使用字段编号。常规行情的 `fields` 可选；资金流订阅必须明确填写字段编号。大单资金流可使用 `money` 设置金额下限。  ```json {   "action": "subscribe",   "kind": "quote",   "market": "USHA",   "code": "600519" } ```  ## 数据消息的公共结构  订阅数据消息的 `event` 为 `data`，具体内容位于 `data`。  ```json {   "event": "data",   "subscription_ids": [1],   "kind": "quote",   "code": 0,   "message": "操作成功",   "data": {     "instance": 123,     "business_type": 10001,     "connection_generation": 1,     "segment_count": 1,     "record_count": 1,     "row_count": 1,     "data_state": "rows_returned",     "format": "hxfile",     "records": [[       {         "5": {"type": "string", "value": "USHA600519"},         "10": {"type": "float", "value": 1480.25}       }     ]]   } } ```  - `subscription_ids`：本条数据对应的订阅编号。同一条数据可能同时对应多个订阅。 - `instance`：行情请求编号，可用于核对数据来源。 - `business_type`：行情数据类型编号。 - `connection_generation`：行情连接代次，断线重连后递增；不是数据序号。短线精灵不返回此字段。 - `segment_count`：本次数据包含的分段数。 - `record_count`：与 `segment_count` 一致，表示本次数据的分段数；记录总数请读取 `row_count`。 - `row_count`：所有分段中的记录总数。判断本次是否有数据应读取此字段。 - `data_state`：`rows_returned` 表示包含记录；`empty_indeterminate` 表示本次没有记录。 - `format`：`hxfile` 和 `hqfile` 为字段记录，`hdfile` 为委托队列，`gbk_string` 为文本，`empty` 表示空数据。 - `records`：按“数据分段 → 记录 → 字段”组织。字段键为字段编号，字段值包含 `type` 和 `value`。  字段值的 `type` 可能为 `string`、`integer`、`float`、`binary`、`integer_array`、`invalid` 或 `no_update`。`invalid` 表示当前值无效，`no_update` 表示本条数据没有更新该字段；这两种情况没有 `value`。  本接口只发送实时变动，不包含历史记录。订阅失败时返回 `notice`。  ## 可订阅内容  ### 实时行情 `quote`  证券的最新价、涨跌、成交量等常用行情字段。`data.business_type` 为 `10001`，`data.records` 使用公共字段记录结构。可通过 `fields` 指定需要返回的字段；省略时使用字段 `5,55,10,48,13,49,7,6,8,9,19,18,12`。  ### 当日分时 `intraday`  证券当日分时行情的持续更新。`data.business_type` 为 `10101`，`data.records` 使用公共字段记录结构；默认字段为 `1,10,13,19,40`。  ### 盘前分时 `pre_market_intraday`  持续接收盘前交易时段的分时行情。`data.business_type` 为 `10101`，默认字段为 `1,10,13,19,40`。美股交易所代码会按行情服务规则自动映射到对应的盘前行情市场；客户端仍使用证券原市场和代码订阅。  ### 日 K 线 `daily_kline`  证券当日日 K 线的持续更新。`data.business_type` 为 `10131`，`data.records` 使用公共字段记录结构；默认字段为 `1,5,7,8,9,10,13,19`。  ### 五档盘口 `depth`  证券买卖五档价格及委托数量。`data.business_type` 为 `10001`，`data.records` 使用公共字段记录结构；字段由证券代码、昨收价及买卖五档价量组成。  ### 逐笔行情 `transaction`  普通行情权限下可用的盘中逐笔成交行情。`data.business_type` 为 `10121`，`data.records` 使用公共字段记录结构；默认字段为 `1,5,10,12,18,49`。服务端会排除盘前和盘后记录。它与需要 Level-2 权限的 `transaction_detail` 不同。  ### 盘前逐笔 `pre_market_transaction`  持续接收盘前交易时段的逐笔成交。`data.business_type` 为 `10121`，默认字段为 `1,5,10,12,18,49`。字段 12 中的 `volclass=8` 表示盘前成交。  ### 盘后逐笔 `post_market_transaction`  持续接收盘后交易时段的逐笔成交。`data.business_type` 为 `10121`，默认字段为 `1,5,10,12,18,49`。字段 12 中的 `volclass=9` 表示盘后成交。  ### 集合竞价 `call_auction`  证券集合竞价期间的行情变化。`data.business_type` 为 `10122`，`data.records` 使用公共字段记录结构；默认字段为 `1,5,10,24,25,27,30,31,33,49`。  ### Level-2 十档盘口 `level2_depth`  证券买卖十档价格及委托数量。需要 Level-2 权限。`data.business_type` 为 `10001`；除公共字段记录外，`data` 还包含：  - `field_semantics`：字段编号与盘口含义的对应关系。 - `depth`：按证券组织的十档盘口数组。 - `depth[].security`：证券代码。 - `depth[].previous_close`：昨收价。 - `depth[].bids`、`depth[].asks`：买一至买十、卖一至卖十；每档包含 `level`、`price` 和 `volume`。  ### Level-2 逐笔成交 `transaction_detail`  逐笔成交明细。需要 Level-2 权限。`data.business_type` 为 `10201`。`records` 保留字段编号记录，`semantic_records` 提供可读字段；每条语义记录包含：  - `values`：价格、数量、成交时间、买卖委托号等已确认字段。 - `source_field_ids`：可读字段名对应的字段编号。 - `derived`：买卖方向、成交金额和标准化时间等派生结果。  可用字段名称为 `source_tick_id`、`market_type`、`full_code`、`price`、`side`、`volclass`、`volume`、`transaction_count`、`raw_transaction_amount`、`trade_time`、`buy_order_no`、`sell_order_no`。`side` 与 `volclass` 都会请求字段 12，重复项会自动合并。成交方向中，`volclass=1` 对应 `side=sell`，`volclass=5` 对应 `side=buy`，其他值为 `unknown`；逐笔成交不提供委托价格类型标记。  ### Level-2 逐笔委托 `order_detail`  逐笔委托明细。需要 Level-2 权限。`data.business_type` 为 `10206`。可用字段名称为 `order_no`、`price`、`side`、`volclass`、`volume`、`amount`、`order_time`、`request_time`。`semantic_records[].values` 包含实际返回的已确认字段；`derived` 包含买卖方向、价格类型和标准化时间。  ### Level-2 买入撤单 `buy_cancel`  买入方向的逐笔撤单记录。需要 Level-2 权限。`data.business_type` 为 `10202`。可用字段名称为 `order_no`、`latest_price`、`price`、`volume`、`amount`、`request_time`、`cancel_time`。`semantic_records[].values` 包含实际返回的已确认字段；`derived.side` 为 `buy`。  ### Level-2 卖出撤单 `sell_cancel`  卖出方向的逐笔撤单记录。需要 Level-2 权限。`data.business_type` 为 `10203`。可用字段名称与买入撤单一致，`derived.side` 为 `sell`。  ### Level-2 买方委托队列 `buy_queue`  买一档的逐项委托数量及队列信息。需要 Level-2 权限。`data.business_type` 为 `10204`，`data.format` 为 `hdfile`，`data.queue_side` 为 `buy`。  `records` 中每条价位记录包含 `market`、`code`、`time`、`price`、`count`、`total`、`volumes` 等字段；`volumes` 是该价位下的逐项委托数量。`segment_metadata` 保留各分段的字段和证券索引信息。  ### Level-2 卖方委托队列 `sell_queue`  卖一档的逐项委托数量及队列信息。需要 Level-2 权限。`data.business_type` 为 `10205`，响应结构与买方委托队列一致，`data.queue_side` 为 `sell`。  ### 短线精灵 `short_line`  持续接收指定市场实时推送的新异动。无需填写 `code` 和 `fields`。  没有新异动时不发送数据消息，连接保持打开。订阅失败时返回 `notice`。`data.business_type` 为 `1700`，异动记录位于 `data.records`。当前样本中的原始字段编号为 `1`（时间原值）、`5`（完整证券代码）、`19`（异动原始值/金额候选）、`55`（证券名称）、`61`（异动类型编号）和 `64`（异动颜色/状态原值）。这些编号必须按短线精灵业务解释，不能套用普通行情或 Level-2 的同名字段；当前也不会因 `semantic=true` 生成短线精灵语义记录。  ```json {   "action": "subscribe",   "kind": "short_line",   "market": "USZA" } ```  ### 个股资金流 `capital_flow`  持续接收指定证券的资金流字段。`data.business_type` 为 `10200`，`data.records` 使用公共字段记录结构。`fields` 必填，取值为行情字段编号。  ```json {   "action": "subscribe",   "kind": "capital_flow",   "market": "USHA",   "code": "600519",   "fields": [1, 10, 13] } ```  ### 大单资金流 `big_order_flow`  持续接收达到金额下限的大单资金流数据。`money` 单位为元，省略时为 `1000000`。`data` 包含 `method`、`format`、`response_info`、`records`、`row_count` 和 `segment_metadata`；大单记录位于 `records`。  ```json {   "action": "subscribe",   "kind": "big_order_flow",   "market": "USZA",   "code": "000001",   "money": 500000 } ```  ### TAS 成交明细 `enhanced_transactions`  持续接收指定证券的 TAS 成交明细，`data.business_type` 为 `10125`。本类型不是普通逐笔成交；请填写目标证券的 `market`、`code` 和 TAS 数字字段编号 `fields`。`records` 使用数字字段编号，不提供普通逐笔的买卖方向或委托编号。  ### 买卖盘排名 `bid_ask_rank`  持续接收指定证券的买卖盘排名变化。需要 Level-2 权限。`data.business_type` 为 `10207`，记录位于 `data.records`。省略 `fields` 时返回价格、证券代码、方向、委托量及排名字段。  ```json {   "action": "subscribe",   "kind": "bid_ask_rank",   "market": "USZA",   "code": "000001",   "fields": [10, 5, 12, 13, 53, 54] } ```  ## 取消订阅  使用订阅成功消息中的 `subscription_id` 取消对应订阅，不影响同一连接中的其他订阅。  ```json {   "action": "unsubscribe",   "subscription_id": 1 } ```  ## 连接检查  客户端可以发送 `ping`，服务端返回 `pong`。  ```json {   "action": "ping" } ```  ## 服务端消息  - `subscribed`：订阅成功，返回 `subscription_id` 和 `kind`；游客行情还会返回 `warnings`。 - `unsubscribed`：取消订阅成功，返回被取消的 `subscription_id`。 - `data`：订阅数据，`subscription_ids` 表示对应的订阅，具体内容位于 `data`。 - `notice`：本次操作或订阅暂时无法完成，`code` 和 `message` 说明结果。 - `pong`：对客户端 `ping` 的响应。  客户端应按 `event` 判断消息类型，不应依赖消息到达顺序区分不同订阅。 ',
                "auth_required": False,
                "level2": True,
            },
            {
                "path": '/v1/market/watch/short-line-events',
                "method": 'GET',
                "summary": '短线精灵实时订阅',
                "description": '持续接收指定市场的新异动，不包含历史记录。没有新异动时连接保持打开。每条事件使用统一的行情响应结构。',
                "auth_required": False,
                "level2": False,
            },
        ],
    },
    {
        "key": 'topics',
        "name": '市场专题',
        "endpoints": [
            {
                "path": '/v1/market/topics/limit-up-statistics',
                "method": 'POST',
                "summary": '涨跌停统计',
                "description": '返回当日与前一交易日的涨停、跌停、开板、触板数量及封板率。可按市场范围筛选，无需登录行情账户。',
                "auth_required": False,
                "level2": False,
            },
        ],
    },
]
