"""sync model metadata drift

Revision ID: 17203a828aab
Revises: 0033
Create Date: 2026-09-16 12:09:28.343383

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '17203a828aab'
down_revision: Union[str, Sequence[str], None] = '0033'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sys_permission',
    sa.Column('id', sa.BigInteger(), nullable=False, comment='雪花算法主键 ID'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='权限名称'),
    sa.Column('code', sa.String(length=100), nullable=False, comment='权限编码（唯一标识符）'),
    sa.Column('description', sa.Text(), nullable=True, comment='权限描述'),
    sa.Column('resource_path', sa.String(length=255), nullable=True, comment='资源路径（如API路径、菜单URL等）'),
    sa.Column('method', sa.String(length=10), nullable=True, comment='请求方法（如GET, POST, PUT, DELETE等）'),
    sa.Column('category', sa.String(length=50), nullable=True, comment='权限分类'),
    sa.Column('type', sa.String(length=20), nullable=False, comment='权限类型：api, menu, button, data等'),
    sa.Column('status', sa.Boolean(), nullable=False, comment='状态：True-启用，False-禁用'),
    sa.Column('sort', sa.Integer(), nullable=False, comment='排序号'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='删除时间，为空则未删除'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='\n    系统权限表\n    存储细粒度的权限点，用于精确的权限控制\n    '
    )
    op.create_index(op.f('ix_sys_permission_code'), 'sys_permission', ['code'], unique=True)
    op.create_index(op.f('ix_sys_permission_id'), 'sys_permission', ['id'], unique=True)
    op.alter_column('business_ai_strategy', 'stock_pool',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='股票池：{"codes": ["600519", ...]}，为空则由 AI 在全市场内自主选择',
               existing_comment='股票池：{"codes": [...]}，为空则由 AI 在全市场内自主选择',
               existing_nullable=True)
    op.drop_index(op.f('ix_ai_strategy_category'), table_name='business_ai_strategy')
    op.create_index(op.f('ix_business_ai_strategy_category'), 'business_ai_strategy', ['category'], unique=False)
    op.alter_column('business_analysis_config', 'analysis_type',
               existing_type=sa.VARCHAR(length=20),
               comment='分析类型：market-大盘分析，sector-板块分析（与 session 联合唯一）',
               existing_comment='分析类型：market-大盘分析，sector-板块分析（唯一）',
               existing_nullable=False)
    op.alter_column('business_analysis_run', 'analysis_type',
               existing_type=sa.VARCHAR(length=20),
               comment='分析类型：market-大盘分析，sector-板块分析，news-每日资讯分析',
               existing_comment='分析类型：market-大盘分析，sector-板块分析',
               existing_nullable=False)
    op.alter_column('business_analysis_run', 'session',
               existing_type=sa.VARCHAR(length=20),
               comment='分析时段：close-收盘分析（16:05），morning-早盘分析（9:20），weekly-周度复盘（周日晚，仅资讯分析）',
               existing_comment='分析时段：close-收盘分析（16:05），morning-早盘分析（9:20）',
               existing_nullable=False,
               existing_server_default=sa.text("'close'::character varying"))
    op.alter_column('business_block_trade_active', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='删除时间，为空则未删除',
               existing_comment='删除时间',
               existing_nullable=True)
    op.alter_column('business_block_trade_daily', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='删除时间，为空则未删除',
               existing_comment='删除时间',
               existing_nullable=True)
    op.alter_column('business_block_trade_sync_log', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='删除时间，为空则未删除',
               existing_comment='删除时间',
               existing_nullable=True)
    op.create_table_comment(
        'business_block_trade_sync_log',
        '\n    大宗交易（暗盘）采集日志表\n    记录每次按子榜抓取的结果，sub_board 区分 daily / active\n    ',
        existing_comment='大宗交易采集日志表',
        schema=None
    )
    op.alter_column('business_board_daily', 'record_date',
               existing_type=sa.DATE(),
               comment='快照日期（本地时区）',
               existing_comment='快照日期',
               existing_nullable=False)
    op.alter_column('business_board_daily', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='删除时间，为空则未删除',
               existing_comment='删除时间',
               existing_nullable=True)
    op.drop_index(op.f('ix_board_stock_daily_date_code'), table_name='business_board_stock_daily')
    op.drop_index(op.f('ix_board_stock_daily_stock_code'), table_name='business_board_stock_daily')
    op.create_index(op.f('ix_business_board_stock_daily_record_date'), 'business_board_stock_daily', ['record_date'], unique=False)
    op.create_index(op.f('ix_business_board_stock_daily_stock_code'), 'business_board_stock_daily', ['stock_code'], unique=False)
    op.alter_column('business_financial_interpretation', 'run_date',
               existing_type=sa.VARCHAR(length=10),
               comment='执行日期 YYYY-MM-DD（定时任务同日去重用）',
               existing_comment='执行日期 YYYY-MM-DD',
               existing_nullable=False)
    op.alter_column('business_financial_interpretation', 'trigger_type',
               existing_type=sa.VARCHAR(length=20),
               comment='触发方式：schedule-定时（持仓自动），manual-手动',
               existing_comment='触发方式：schedule-定时，manual-手动',
               existing_nullable=False)
    op.alter_column('business_financial_interpretation', 'status',
               existing_type=sa.VARCHAR(length=20),
               comment='执行状态：running-执行中，success-成功，failed-失败',
               existing_comment='执行状态：running/success/failed',
               existing_nullable=False)
    op.alter_column('business_financial_report', 'report_period',
               existing_type=sa.VARCHAR(length=10),
               comment='报告期 YYYY-MM-DD（如 2026-06-30）',
               existing_comment='报告期 YYYY-MM-DD',
               existing_nullable=False)
    op.alter_column('business_financial_report', 'metrics',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='财报关键指标（营收/净利/同比/ROE/毛利率等，列名→值）',
               existing_comment='财报关键指标（列名→值）',
               existing_nullable=True)
    op.alter_column('business_limit_up_stock', 'record_date',
               existing_type=sa.DATE(),
               comment='快照日期（本地时区）',
               existing_comment='快照日期',
               existing_nullable=False)
    op.alter_column('business_limit_up_stock', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='删除时间，为空则未删除',
               existing_comment='删除时间',
               existing_nullable=True)
    op.create_table_comment(
        'business_limit_up_stock',
        '涨停/炸板股池日快照表',
        existing_comment='涨停股池日快照表',
        schema=None
    )
    op.alter_column('business_macro_indicator', 'indicator_name',
               existing_type=sa.VARCHAR(length=50),
               comment='指标中文名：居民消费价格指数 等',
               existing_comment='指标中文名',
               existing_nullable=False)
    op.alter_column('business_macro_indicator', 'unit',
               existing_type=sa.VARCHAR(length=20),
               comment='单位：% / 亿元 / 亿美元等',
               existing_comment='单位',
               existing_nullable=False,
               existing_server_default=sa.text("'%%'::character varying"))
    op.alter_column('business_market_index_daily', 'record_date',
               existing_type=sa.DATE(),
               comment='快照日期（本地时区）',
               existing_comment='快照日期',
               existing_nullable=False)
    op.alter_column('business_market_index_daily', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='删除时间，为空则未删除',
               existing_comment='删除时间',
               existing_nullable=True)
    op.alter_column('business_research_report', 'forecast',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='盈利预测：{年份: {eps, pe}}（东财预测收益/市盈率）',
               existing_comment='盈利预测：{年份: {eps, pe}}',
               existing_nullable=True)
    op.alter_column('business_stock_hot_sync_log', 'status',
               existing_type=sa.BOOLEAN(),
               comment='采集状态：True-成功，False-失败',
               existing_comment='采集状态',
               existing_nullable=False)
    op.alter_column('business_stock_hot_sync_log', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='删除时间，为空则未删除',
               existing_comment='删除时间',
               existing_nullable=True)
    op.create_table_comment(
        'business_stock_hot_sync_log',
        '\n    股票热榜采集日志表\n    记录每次按源抓取的结果\n    ',
        existing_comment='股票热榜采集日志表',
        schema=None
    )
    op.alter_column('business_strategy_position', 'status',
               existing_type=sa.VARCHAR(length=20),
               comment='持仓状态：holding-持仓中，closed-已平仓，cancelled-已取消',
               existing_comment='持仓状态：holding/closed/cancelled',
               existing_nullable=False)
    op.alter_column('business_strategy_position', 'sell_reason',
               existing_type=sa.VARCHAR(length=500),
               comment='卖出原因：stop_loss/target_reached/trailing_stop/ai_signal/manual',
               existing_comment='卖出原因：stop_loss/take_profit/target_reached/ai_signal/manual',
               existing_nullable=True)
    op.alter_column('business_strategy_run', 'opened_count',
               existing_type=sa.INTEGER(),
               comment='新建仓数量（交易引擎执行信号时累加）',
               existing_comment='本次新建仓数量',
               existing_nullable=False)
    op.alter_column('business_strategy_run', 'closed_count',
               existing_type=sa.INTEGER(),
               comment='平仓数量（交易引擎执行信号时累加）',
               existing_comment='本次平仓数量',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('business_strategy_run', 'closed_count',
               existing_type=sa.INTEGER(),
               comment='本次平仓数量',
               existing_comment='平仓数量（交易引擎执行信号时累加）',
               existing_nullable=False)
    op.alter_column('business_strategy_run', 'opened_count',
               existing_type=sa.INTEGER(),
               comment='本次新建仓数量',
               existing_comment='新建仓数量（交易引擎执行信号时累加）',
               existing_nullable=False)
    op.alter_column('business_strategy_position', 'sell_reason',
               existing_type=sa.VARCHAR(length=500),
               comment='卖出原因：stop_loss/take_profit/target_reached/ai_signal/manual',
               existing_comment='卖出原因：stop_loss/target_reached/trailing_stop/ai_signal/manual',
               existing_nullable=True)
    op.alter_column('business_strategy_position', 'status',
               existing_type=sa.VARCHAR(length=20),
               comment='持仓状态：holding/closed/cancelled',
               existing_comment='持仓状态：holding-持仓中，closed-已平仓，cancelled-已取消',
               existing_nullable=False)
    op.create_table_comment(
        'business_stock_hot_sync_log',
        '股票热榜采集日志表',
        existing_comment='\n    股票热榜采集日志表\n    记录每次按源抓取的结果\n    ',
        schema=None
    )
    op.alter_column('business_stock_hot_sync_log', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='删除时间',
               existing_comment='删除时间，为空则未删除',
               existing_nullable=True)
    op.alter_column('business_stock_hot_sync_log', 'status',
               existing_type=sa.BOOLEAN(),
               comment='采集状态',
               existing_comment='采集状态：True-成功，False-失败',
               existing_nullable=False)
    op.alter_column('business_research_report', 'forecast',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='盈利预测：{年份: {eps, pe}}',
               existing_comment='盈利预测：{年份: {eps, pe}}（东财预测收益/市盈率）',
               existing_nullable=True)
    op.alter_column('business_market_index_daily', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='删除时间',
               existing_comment='删除时间，为空则未删除',
               existing_nullable=True)
    op.alter_column('business_market_index_daily', 'record_date',
               existing_type=sa.DATE(),
               comment='快照日期',
               existing_comment='快照日期（本地时区）',
               existing_nullable=False)
    op.alter_column('business_macro_indicator', 'unit',
               existing_type=sa.VARCHAR(length=20),
               comment='单位',
               existing_comment='单位：% / 亿元 / 亿美元等',
               existing_nullable=False,
               existing_server_default=sa.text("'%%'::character varying"))
    op.alter_column('business_macro_indicator', 'indicator_name',
               existing_type=sa.VARCHAR(length=50),
               comment='指标中文名',
               existing_comment='指标中文名：居民消费价格指数 等',
               existing_nullable=False)
    op.create_table_comment(
        'business_limit_up_stock',
        '涨停股池日快照表',
        existing_comment='涨停/炸板股池日快照表',
        schema=None
    )
    op.alter_column('business_limit_up_stock', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='删除时间',
               existing_comment='删除时间，为空则未删除',
               existing_nullable=True)
    op.alter_column('business_limit_up_stock', 'record_date',
               existing_type=sa.DATE(),
               comment='快照日期',
               existing_comment='快照日期（本地时区）',
               existing_nullable=False)
    op.alter_column('business_financial_report', 'metrics',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='财报关键指标（列名→值）',
               existing_comment='财报关键指标（营收/净利/同比/ROE/毛利率等，列名→值）',
               existing_nullable=True)
    op.alter_column('business_financial_report', 'report_period',
               existing_type=sa.VARCHAR(length=10),
               comment='报告期 YYYY-MM-DD',
               existing_comment='报告期 YYYY-MM-DD（如 2026-06-30）',
               existing_nullable=False)
    op.alter_column('business_financial_interpretation', 'status',
               existing_type=sa.VARCHAR(length=20),
               comment='执行状态：running/success/failed',
               existing_comment='执行状态：running-执行中，success-成功，failed-失败',
               existing_nullable=False)
    op.alter_column('business_financial_interpretation', 'trigger_type',
               existing_type=sa.VARCHAR(length=20),
               comment='触发方式：schedule-定时，manual-手动',
               existing_comment='触发方式：schedule-定时（持仓自动），manual-手动',
               existing_nullable=False)
    op.alter_column('business_financial_interpretation', 'run_date',
               existing_type=sa.VARCHAR(length=10),
               comment='执行日期 YYYY-MM-DD',
               existing_comment='执行日期 YYYY-MM-DD（定时任务同日去重用）',
               existing_nullable=False)
    op.drop_index(op.f('ix_business_board_stock_daily_stock_code'), table_name='business_board_stock_daily')
    op.drop_index(op.f('ix_business_board_stock_daily_record_date'), table_name='business_board_stock_daily')
    op.create_index(op.f('ix_board_stock_daily_stock_code'), 'business_board_stock_daily', ['stock_code'], unique=False)
    op.create_index(op.f('ix_board_stock_daily_date_code'), 'business_board_stock_daily', ['record_date', 'board_code'], unique=False)
    op.alter_column('business_board_daily', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='删除时间',
               existing_comment='删除时间，为空则未删除',
               existing_nullable=True)
    op.alter_column('business_board_daily', 'record_date',
               existing_type=sa.DATE(),
               comment='快照日期',
               existing_comment='快照日期（本地时区）',
               existing_nullable=False)
    op.create_table_comment(
        'business_block_trade_sync_log',
        '大宗交易采集日志表',
        existing_comment='\n    大宗交易（暗盘）采集日志表\n    记录每次按子榜抓取的结果，sub_board 区分 daily / active\n    ',
        schema=None
    )
    op.alter_column('business_block_trade_sync_log', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='删除时间',
               existing_comment='删除时间，为空则未删除',
               existing_nullable=True)
    op.alter_column('business_block_trade_daily', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='删除时间',
               existing_comment='删除时间，为空则未删除',
               existing_nullable=True)
    op.alter_column('business_block_trade_active', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='删除时间',
               existing_comment='删除时间，为空则未删除',
               existing_nullable=True)
    op.alter_column('business_analysis_run', 'session',
               existing_type=sa.VARCHAR(length=20),
               comment='分析时段：close-收盘分析（16:05），morning-早盘分析（9:20）',
               existing_comment='分析时段：close-收盘分析（16:05），morning-早盘分析（9:20），weekly-周度复盘（周日晚，仅资讯分析）',
               existing_nullable=False,
               existing_server_default=sa.text("'close'::character varying"))
    op.alter_column('business_analysis_run', 'analysis_type',
               existing_type=sa.VARCHAR(length=20),
               comment='分析类型：market-大盘分析，sector-板块分析',
               existing_comment='分析类型：market-大盘分析，sector-板块分析，news-每日资讯分析',
               existing_nullable=False)
    op.alter_column('business_analysis_config', 'analysis_type',
               existing_type=sa.VARCHAR(length=20),
               comment='分析类型：market-大盘分析，sector-板块分析（唯一）',
               existing_comment='分析类型：market-大盘分析，sector-板块分析（与 session 联合唯一）',
               existing_nullable=False)
    op.drop_index(op.f('ix_business_ai_strategy_category'), table_name='business_ai_strategy')
    op.create_index(op.f('ix_ai_strategy_category'), 'business_ai_strategy', ['category'], unique=False)
    op.alter_column('business_ai_strategy', 'stock_pool',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='股票池：{"codes": [...]}，为空则由 AI 在全市场内自主选择',
               existing_comment='股票池：{"codes": ["600519", ...]}，为空则由 AI 在全市场内自主选择',
               existing_nullable=True)
    op.drop_index(op.f('ix_sys_permission_id'), table_name='sys_permission')
    op.drop_index(op.f('ix_sys_permission_code'), table_name='sys_permission')
    op.drop_table('sys_permission')
    # ### end Alembic commands ###
